### ISSUE TITLE
How do I use this software

### ISSUE THREAD

**Issue by MissBaker** [ribbons/RadioDownloader#199]
I have downloaded this as I want to record a particular radio program from iplayer. When I open it however only rss feed comes up. I don't need to record from rss feeds only iplayer. There is no help at all on how to use it (help just tells you to select from the list which only includes RSS) and the interface is not clear at all. Very disappointing experience and waste of my time installing.

**Comment by ribbons** [comment]
Radio Downloader only downloads RSS feeds since I had a letter from the BBC's legal department in 2013 (see https://nerdoftheherd.com/news/2013/06/26/radio-downloader-and-bbc-radio/).

Is there an mention somewhere on my site or here which incorrectly states that it downloads iplayer content from the BBC?
